### ISSUE TITLE
Module 2 and 3 PatrolCar2 still gives issues

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/20776-Performing-Big-Data-Engineering-on-Microsoft-Cloud-Services-#28]
It is issued a few times, but PatrolCar2 still gives issues (local, LOD, ...). PatrolCar2 times out and doesn't produce any data.

Its blocking and holds up the class for all students. We are not able to make it work. Its hard to find out what could be the problem.

Marcel

**Comment by JohnPWSharp** [comment]
This sounds like a connectivity issue between the PatrolCar2 app and Azure. Can you verify the environment in which you are running - Gateway VM + desktop VM (20776A-LON-DEV) + desktop DC (20776A-LON-DC), or Learn on Demand VMs

**Comment by JohnPWSharp** [comment]
Additionally, can you run the app in debug mode and post the details of any exceptions that occur. Finally, can you make sure that the "plumbing" is correct, and that the ASA jobs are configured to send the appropriate data to the correct outputs (a common problem seems to be invalid data appearing in the Service Bus Topic sent to the Patrol Cars app, due to a misconfiguration of the ASA job)

**Comment by JohnPWSharp** [comment]
After further investigation, it is important to ensure that the VM is configured with sufficient virtual processors (at least 4), as described at the start of the lab. Additionally, I have found that the performance of ASA seems to vary markedly between regions - if in doubt, use East US 2.
